# Generated by Django 3.2 on 2022-08-29 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('croppedImage', models.ImageField(blank=True, null=True, upload_to='cropped')),
            ],
        ),
    ]
