# Generated by Django 3.2 on 2022-09-06 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(blank=True, null=True, upload_to='documents')),
                ('image', models.ImageField(blank=True, null=True, upload_to='documents/images')),
                ('verified', models.BooleanField(default=False)),
            ],
        ),
    ]
