# Generated by Django 3.2 on 2022-09-06 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdf',
            name='launguage',
            field=models.CharField(blank=True, choices=[('eng', 'eng'), ('chi_sim', 'chi_sim')], max_length=255, null=True),
        ),
    ]
