# Generated by Django 3.2 on 2022-09-06 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_pdf_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdf',
            name='c_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.uimage'),
        ),
    ]
